apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: p2p-av
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: p2p-av
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
