apiVersion: v1
kind: Service
metadata:
  name: signaling
  namespace: p2p-av
  labels:
    app.kubernetes.io/name: signaling
    app.kubernetes.io/part-of: p2p-av
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: signaling
  ports:
    - name: https
      port: 8443
      targetPort: https
      nodePort: 30443
      protocol: TCP
