apiVersion: v1
kind: Secret
metadata:
  name: p2p-secrets
  namespace: p2p-av
  labels:
    app.kubernetes.io/part-of: p2p-av
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_jwt_secret_32chars_min"
  admin-secret: "CHANGE_ME_admin_secret"
  turn-secret: "CHANGE_ME_turn_shared_secret"
